// frontend/src/routes/setup/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import type { WiFiNetwork, SavedNetwork } from '$lib/types';
	import {
		networks,
		isScanning,
		isConnecting,
		error,
		connectionProgress,
		savedNetworks,
		isLoadingSaved,
		scanNetworks,
		connectToNetwork,
		getSavedNetworks,
		forgetNetwork,
		resetToHotspot,
		getSignalColor,
		requiresPassword
	} from '$lib/stores/wifi';

	// Combined network with saved status
	interface CombinedNetwork extends WiFiNetwork {
		isSaved?: boolean;
		isCurrent?: boolean;
		savedId?: number;
	}

	let selectedNetwork: CombinedNetwork | null = null;
	let password = '';
	let showPassword = false;
	let confirmingForget = false;
	let confirmingReset = false;

	// Combine available networks with saved network info
	$: combinedNetworks = $networks.map((network) => {
		const savedNetwork = $savedNetworks.find((s) => s.ssid === network.ssid);
		return {
			...network,
			isSaved: !!savedNetwork,
			isCurrent: savedNetwork?.current || false,
			savedId: savedNetwork?.id
		} as CombinedNetwork;
	});

	onMount(() => {
		scanNetworks();
		getSavedNetworks();
	});

	const handleNetworkClick = (network: CombinedNetwork) => {
		selectedNetwork = network;
		password = '';
		confirmingForget = false;
	};

	const handleConnect = async () => {
		if (!selectedNetwork) return;

		const success = await connectToNetwork({
			ssid: selectedNetwork.ssid,
			password: password,
			security: selectedNetwork.security
		});

		if (success) {
			selectedNetwork = null;
			password = '';
		}
	};

	const handleForget = async () => {
		if (!selectedNetwork?.savedId) return;

		const success = await forgetNetwork(selectedNetwork.savedId, selectedNetwork.ssid);

		if (success) {
			selectedNetwork = null;
			confirmingForget = false;
			// Refresh both lists
			await getSavedNetworks();
			await scanNetworks();
		}
	};

	const closeDialog = () => {
		selectedNetwork = null;
		password = '';
		confirmingForget = false;
	};

	const handleResetToHotspot = async () => {
		const success = await resetToHotspot();
		if (success) {
			// System will reboot - show message
			confirmingReset = false;
		}
	};
</script>

<svelte:head>
	<title>Radio WiFi - WiFi Manager</title>
</svelte:head>

<div class="min-h-screen bg-gray-50 dark:bg-gray-900">
	<!-- Header -->
	<header class="bg-white dark:bg-gray-800 shadow">
		<div class="max-w-md mx-auto px-4">
			<div class="flex items-center justify-between py-4">
				<div class="flex items-center space-x-3">
					<button on:click={() => goto('/')} class="btn-secondary p-2">
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M10 19l-7-7m0 0l7-7m-7 7h18"
							/>
						</svg>
					</button>
					<div>
						<h1 class="text-xl font-bold text-gray-900 dark:text-white">WiFi Manager</h1>
						<p class="text-sm text-gray-500 dark:text-gray-400">
							Connect to networks and manage WiFi
						</p>
					</div>
				</div>
				<button
					on:click={() => {
						scanNetworks();
						getSavedNetworks();
					}}
					disabled={$isScanning || $isLoadingSaved}
					class="btn-secondary p-2"
					title="Refresh networks"
				>
					<svg
						class="w-4 h-4"
						class:animate-spin={$isScanning || $isLoadingSaved}
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
						/>
					</svg>
				</button>
			</div>
		</div>
	</header>

	<!-- Main Content -->
	<main class="max-w-md mx-auto px-4 py-6">
		<!-- Error Display -->
		{#if $error}
			<div
				class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 mb-6"
			>
				<div class="flex items-center">
					<svg
						class="w-5 h-5 text-red-400 mr-2"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
						/>
					</svg>
					<p class="text-red-800 dark:text-red-200 text-sm">{$error}</p>
				</div>
			</div>
		{/if}

		<!-- Connection Progress -->
		{#if $connectionProgress.status !== 'idle'}
			<div
				class="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-6"
			>
				<div class="flex items-start">
					{#if $connectionProgress.status === 'connecting' || $connectionProgress.status === 'verifying'}
						<svg
							class="animate-spin h-5 w-5 text-blue-600 dark:text-blue-400 mt-0.5"
							fill="none"
							viewBox="0 0 24 24"
						>
							<circle
								class="opacity-25"
								cx="12"
								cy="12"
								r="10"
								stroke="currentColor"
								stroke-width="4"
							/>
							<path
								class="opacity-75"
								fill="currentColor"
								d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
							/>
						</svg>
					{:else if $connectionProgress.status === 'success'}
						<svg
							class="h-5 w-5 text-green-600 dark:text-green-400 mt-0.5"
							fill="currentColor"
							viewBox="0 0 20 20"
						>
							<path
								fill-rule="evenodd"
								d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
								clip-rule="evenodd"
							/>
						</svg>
					{:else if $connectionProgress.status === 'failed'}
						<svg
							class="h-5 w-5 text-red-600 dark:text-red-400 mt-0.5"
							fill="currentColor"
							viewBox="0 0 20 20"
						>
							<path
								fill-rule="evenodd"
								d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
								clip-rule="evenodd"
							/>
						</svg>
					{/if}
					<div class="ml-3 flex-1">
						<p
							class="text-sm font-medium {$connectionProgress.status === 'success'
								? 'text-green-600 dark:text-green-400'
								: $connectionProgress.status === 'failed'
									? 'text-red-600 dark:text-red-400'
									: 'text-blue-600 dark:text-blue-400'}"
						>
							{$connectionProgress.message}
						</p>
						{#if $connectionProgress.maxAttempts > 1}
							<p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
								Attempt {$connectionProgress.attempt}/{$connectionProgress.maxAttempts}
							</p>
						{/if}
					</div>
				</div>
			</div>
		{/if}

		<!-- Networks List -->
		<div class="card mb-6">
			<div class="p-4 border-b border-gray-200 dark:border-gray-700">
				<h2 class="text-lg font-semibold text-gray-900 dark:text-white">WiFi Networks</h2>
			</div>

			<div class="max-h-96 overflow-y-auto">
				{#if $isScanning}
					<div class="p-6 text-center">
						<svg
							class="w-8 h-8 animate-spin text-primary-600 mx-auto mb-4"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
							/>
						</svg>
						<p class="text-gray-600 dark:text-gray-400">Scanning for networks...</p>
					</div>
				{:else if combinedNetworks.length === 0}
					<div class="p-6 text-center">
						<svg
							class="w-8 h-8 text-gray-400 mx-auto mb-4"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M9.172 16.172a4 4 0 015.656 0M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
							/>
						</svg>
						<p class="text-gray-600 dark:text-gray-400">No networks found</p>
						<button on:click={() => { scanNetworks(); getSavedNetworks(); }} class="btn-primary mt-4">
							Scan Again
						</button>
					</div>
				{:else}
					{#each combinedNetworks as network}
						<button
							on:click={() => handleNetworkClick(network)}
							class="w-full px-4 py-3 text-left hover:bg-gray-50 dark:hover:bg-gray-700 border-b border-gray-200 dark:border-gray-700 last:border-b-0 transition-colors"
						>
							<div class="flex items-center justify-between">
								<div class="flex-1">
									<div class="flex items-center space-x-2">
										<span class="font-medium text-gray-900 dark:text-white">
											{network.ssid}
										</span>

										<!-- Security Icon -->
										{#if network.security !== 'Open'}
											<svg
												class="w-4 h-4 text-gray-400"
												fill="none"
												stroke="currentColor"
												viewBox="0 0 24 24"
											>
												<path
													stroke-linecap="round"
													stroke-linejoin="round"
													stroke-width="2"
													d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
												/>
											</svg>
										{/if}

										<!-- Current Connection Badge -->
										{#if network.isCurrent}
											<span
												class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400"
											>
												Connected
											</span>
										{:else if network.isSaved}
											<span
												class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400"
											>
												Saved
											</span>
										{/if}
									</div>
									<p class="text-sm text-gray-500 dark:text-gray-400">{network.security}</p>
								</div>
								<div class="flex items-center space-x-2">
									<span class="text-sm {getSignalColor(network.signal)}">{network.signal}%</span>
									<svg
										class="w-4 h-4 {getSignalColor(network.signal)}"
										fill="none"
										stroke="currentColor"
										viewBox="0 0 24 24"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0"
										/>
									</svg>
								</div>
							</div>
						</button>
					{/each}
				{/if}
			</div>
		</div>

		<!-- Action Dialog -->
		{#if selectedNetwork}
			<div class="card p-6">
				<h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">
					{selectedNetwork.ssid}
				</h3>

				{#if selectedNetwork.isCurrent}
					<!-- Currently Connected - Show Forget Option -->
					{#if confirmingForget}
						<div class="space-y-4">
							<p class="text-sm text-gray-600 dark:text-gray-400">
								Are you sure you want to forget this network? You'll need to re-enter the password
								to connect again.
							</p>
							<div class="flex space-x-3">
								<button on:click={() => (confirmingForget = false)} class="btn-secondary flex-1">
									Cancel
								</button>
								<button on:click={handleForget} class="btn-primary flex-1 bg-red-600 hover:bg-red-700">
									Forget Network
								</button>
							</div>
						</div>
					{:else}
						<div class="space-y-4">
							<div class="flex items-center space-x-2 text-green-600 dark:text-green-400">
								<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
									<path
										fill-rule="evenodd"
										d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
										clip-rule="evenodd"
									/>
								</svg>
								<span class="text-sm font-medium">Currently connected to this network</span>
							</div>
							<div class="flex space-x-3">
								<button on:click={closeDialog} class="btn-secondary flex-1">Close</button>
								<button on:click={() => (confirmingForget = true)} class="btn-secondary flex-1">
									Forget Network
								</button>
							</div>
						</div>
					{/if}
				{:else if selectedNetwork.isSaved}
					<!-- Saved Network - Quick Reconnect -->
					<div class="space-y-4">
						<p class="text-sm text-gray-600 dark:text-gray-400">
							This network is saved. Connect using the saved password.
						</p>
						<div class="flex space-x-3">
							<button on:click={closeDialog} class="btn-secondary flex-1">Cancel</button>
							<button
								on:click={handleConnect}
								class="btn-primary flex-1"
								disabled={$isConnecting}
							>
								{#if $isConnecting}
									<svg
										class="w-4 h-4 animate-spin mr-2"
										fill="none"
										stroke="currentColor"
										viewBox="0 0 24 24"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
										/>
									</svg>
									Connecting...
								{:else}
									Connect
								{/if}
							</button>
						</div>
					</div>
				{:else}
					<!-- New Network - Ask for Password -->
					{#if requiresPassword(selectedNetwork)}
						<div class="mb-4">
							<label
								for="password"
								class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
							>
								Password
							</label>
							<div class="relative">
								{#if showPassword}
									<input
										id="password"
										type="text"
										bind:value={password}
										placeholder="Enter WiFi password"
										class="input pr-10"
										disabled={$isConnecting}
									/>
								{:else}
									<input
										id="password"
										type="password"
										bind:value={password}
										placeholder="Enter WiFi password"
										class="input pr-10"
										disabled={$isConnecting}
									/>
								{/if}
								<button
									type="button"
									on:click={() => (showPassword = !showPassword)}
									class="absolute inset-y-0 right-0 pr-3 flex items-center"
								>
									{#if showPassword}
										<svg
											class="w-5 h-5 text-gray-400"
											fill="none"
											stroke="currentColor"
											viewBox="0 0 24 24"
										>
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.878 9.878L3 3m6.878 6.878L21 21"
											/>
										</svg>
									{:else}
										<svg
											class="w-5 h-5 text-gray-400"
											fill="none"
											stroke="currentColor"
											viewBox="0 0 24 24"
										>
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
											/>
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
											/>
										</svg>
									{/if}
								</button>
							</div>
						</div>
					{:else}
						<p class="text-sm text-gray-600 dark:text-gray-400 mb-4">
							This is an open network. No password required.
						</p>
					{/if}

					<div class="flex space-x-3">
						<button on:click={closeDialog} class="btn-secondary flex-1" disabled={$isConnecting}>
							Cancel
						</button>
						<button
							on:click={handleConnect}
							class="btn-primary flex-1"
							disabled={$isConnecting || (requiresPassword(selectedNetwork) && !password.trim())}
						>
							{#if $isConnecting}
								<svg
									class="w-4 h-4 animate-spin mr-2"
									fill="none"
									stroke="currentColor"
									viewBox="0 0 24 24"
								>
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										stroke-width="2"
										d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
									/>
								</svg>
								Connecting...
							{:else}
								Connect
							{/if}
						</button>
					</div>
				{/if}
			</div>
		{/if}

		<!-- Reset to Hotspot Button -->
		<div class="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
			{#if confirmingReset}
				<div class="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
					<div class="flex items-start">
						<svg class="w-5 h-5 text-yellow-600 dark:text-yellow-400 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
							<path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
						</svg>
						<div class="ml-3 flex-1">
							<h3 class="text-sm font-medium text-yellow-800 dark:text-yellow-400">
								Reset to Hotspot Mode?
							</h3>
							<div class="mt-2 text-sm text-yellow-700 dark:text-yellow-300">
								<p>This will:</p>
								<ul class="list-disc list-inside mt-1 space-y-1">
									<li>Disconnect from current WiFi network</li>
									<li>Enable hotspot mode (SSID: Radio-Setup)</li>
									<li>Reboot the system</li>
								</ul>
								<p class="mt-2">After reboot, connect to "Radio-Setup" network and navigate to <strong>http://radiod.local</strong></p>
							</div>
							<div class="mt-4 flex space-x-3">
								<button
									on:click={handleResetToHotspot}
									class="px-4 py-2 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700 text-sm font-medium"
								>
									Yes, Reset to Hotspot
								</button>
								<button
									on:click={() => confirmingReset = false}
									class="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 text-sm font-medium"
								>
									Cancel
								</button>
							</div>
						</div>
					</div>
				</div>
			{:else}
				<button
					on:click={() => confirmingReset = true}
					class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 flex items-center justify-center space-x-2"
				>
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0" />
					</svg>
					<span>Reset to Hotspot Mode</span>
				</button>
			{/if}
		</div>
	</main>
</div>

// app/pages/setup.vue
<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900">
    <!-- Header -->
    <header class="bg-white dark:bg-gray-800 shadow">
      <div class="max-w-md mx-auto px-4">
        <div class="flex items-center justify-between py-4">
          <div class="flex items-center space-x-3">
            <button
              @click="navigateTo('/')"
              class="inline-flex items-center px-2 py-2 border border-gray-300 rounded-md text-sm text-gray-700 bg-white hover:bg-gray-50 focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
              </svg>
            </button>
            <div>
              <h1 class="text-xl font-bold text-gray-900 dark:text-white">
                WiFi Setup
              </h1>
              <p class="text-sm text-gray-500 dark:text-gray-400">
                Configure your WiFi connection
              </p>
            </div>
          </div>
          <button
            @click="handleScanNetworks"
            :disabled="isScanning"
            class="inline-flex items-center px-2 py-2 border border-gray-300 rounded-md text-sm text-gray-700 bg-white hover:bg-gray-50 focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg class="w-4 h-4" :class="{ 'animate-spin': isScanning }" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
          </button>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-md mx-auto px-4 py-6 space-y-6">
      <!-- Error Display -->
      <div v-if="error" class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-red-400" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800 dark:text-red-200">
              Connection Error
            </h3>
            <div class="mt-2 text-sm text-red-700 dark:text-red-300">
              <p>{{ error }}</p>
            </div>
            <div class="mt-4">
              <button
                @click="clearError"
                type="button"
                class="bg-red-50 dark:bg-red-900/20 px-2 py-1.5 rounded-md text-sm font-medium text-red-800 dark:text-red-200 hover:bg-red-100 dark:hover:bg-red-900/40 focus:outline-none focus:ring-2 focus:ring-red-600"
              >
                Dismiss
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Success Message -->
      <div v-if="successMessage" class="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-green-800 dark:text-green-200">
              Success
            </h3>
            <div class="mt-2 text-sm text-green-700 dark:text-green-300">
              <p>{{ successMessage }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Current Status -->
      <div v-if="currentStatus" class="bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-700">
        <div class="p-6">
          <div class="flex items-center justify-between mb-4">
            <h2 class="text-lg font-semibold text-gray-900 dark:text-white">
              Current Status
            </h2>
            <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
              :class="statusBadgeClass">
              {{ statusText }}
            </span>
          </div>

          <div class="space-y-3" v-if="currentStatus.status === 'connected' && currentStatus.ssid">
            <div class="flex items-center justify-between">
              <span class="text-sm font-medium text-gray-700 dark:text-gray-300">Network</span>
              <span class="text-sm text-gray-900 dark:text-white font-mono">
                {{ currentStatus.ssid }}
              </span>
            </div>
            <div class="flex items-center justify-between">
              <span class="text-sm font-medium text-gray-700 dark:text-gray-300">IP Address</span>
              <span class="text-sm text-gray-900 dark:text-white font-mono">
                {{ currentStatus.ip || 'N/A' }}
              </span>
            </div>
            <div class="flex items-center justify-between" v-if="currentStatus.signal">
              <span class="text-sm font-medium text-gray-700 dark:text-gray-300">Signal Strength</span>
              <div class="flex items-center space-x-2">
                <span class="text-sm text-gray-600 dark:text-gray-400">
                  {{ Math.round(currentStatus.signal) }}%
                </span>
                <div class="flex space-x-0.5">
                  <div v-for="i in 4" :key="i"
                       class="w-1 bg-gray-300 dark:bg-gray-600 rounded-sm"
                       :class="[
                         i <= Math.ceil((currentStatus.signal || 0) / 25) ? 'bg-green-500' : '',
                         i === 1 ? 'h-2' : i === 2 ? 'h-3' : i === 3 ? 'h-4' : 'h-5'
                       ]">
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-else class="text-center py-4">
            <svg class="w-12 h-12 text-gray-400 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 5.636l-12.728 12.728m0 0L12 12m-6.364 6.364L12 12"></path>
            </svg>
            <p class="text-sm font-medium text-gray-900 dark:text-white mb-1">
              {{ currentStatus.mode === 'hotspot' ? 'Hotspot Mode' : 'Not Connected' }}
            </p>
            <p class="text-xs text-gray-500">
              {{ currentStatus.mode === 'hotspot' ? 'Choose a network below to connect' : 'Choose a network below to connect' }}
            </p>
          </div>
        </div>
      </div>

      <!-- Scanning Status -->
      <div v-if="isScanning" class="bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-700">
        <div class="p-6 text-center">
          <div class="inline-block w-6 h-6 border-2 border-gray-300 border-t-blue-600 rounded-full animate-spin mx-auto mb-3"></div>
          <p class="text-sm text-gray-600 dark:text-gray-400">
            Scanning for WiFi networks...
          </p>
        </div>
      </div>

      <!-- Available Networks -->
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-700">
        <div class="p-6">
          <div class="flex items-center justify-between mb-4">
            <h2 class="text-lg font-semibold text-gray-900 dark:text-white">
              Available Networks
            </h2>
            <div class="flex items-center space-x-2">
              <span class="text-xs text-gray-500" v-if="lastScanTime">
                {{ formatScanTime(lastScanTime) }}
              </span>
              <span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300" v-if="networks.length > 0">
                {{ networks.length }} found
              </span>
            </div>
          </div>

          <!-- No Networks Found -->
          <div v-if="!isScanning && networks.length === 0" class="text-center py-8">
            <svg class="w-12 h-12 text-gray-400 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
            <p class="text-sm font-medium text-gray-900 dark:text-white mb-1">
              No networks found
            </p>
            <p class="text-xs text-gray-500 mb-4">
              Make sure WiFi is enabled and try scanning again
            </p>
            <button
              @click="handleScanNetworks"
              class="inline-flex items-center px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600"
            >
              Try Again
            </button>
          </div>

          <!-- Networks List -->
          <div v-else-if="!isScanning && networks.length > 0" class="space-y-2">
            <div
              v-for="network in networks"
              :key="network.ssid + network.bssid"
              @click="selectNetwork(network)"
              class="flex items-center justify-between p-3 border border-gray-200 dark:border-gray-700 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer transition-colors"
              :class="{ 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-700': selectedNetwork?.ssid === network.ssid }"
            >
              <div class="flex items-center space-x-3">
                <!-- Signal strength icon -->
                <div class="flex flex-col space-y-0.5">
                  <div v-for="i in 4" :key="i"
                       class="w-1 bg-gray-300 dark:bg-gray-600 rounded-sm"
                       :class="[
                         i <= Math.ceil((network.signal || 0) / 25) ? getSignalColor(network.signal) : '',
                         i === 1 ? 'h-1' : i === 2 ? 'h-2' : i === 3 ? 'h-3' : 'h-4'
                       ]">
                  </div>
                </div>
                <div>
                  <div class="flex items-center space-x-2">
                    <p class="text-sm font-medium text-gray-900 dark:text-white">
                      {{ network.ssid }}
                    </p>
                    <svg v-if="network.security !== 'Open'" class="w-3 h-3 text-gray-500" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <div class="flex items-center space-x-2 text-xs text-gray-500">
                    <span>{{ network.security }}</span>
                    <span>•</span>
                    <span>{{ network.signal }}%</span>
                    <span v-if="network.frequency">•</span>
                    <span v-if="network.frequency">{{ network.frequency }}</span>
                  </div>
                </div>
              </div>
              <div class="flex items-center space-x-2">
                <span v-if="network.saved" class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200">
                  Saved
                </span>
                <span v-if="network.connected" class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200">
                  Connected
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Connection Form -->
      <div v-if="selectedNetwork && !selectedNetwork.connected" class="bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-700">
        <div class="p-6">
          <div class="flex items-center justify-between mb-4">
            <h2 class="text-lg font-semibold text-gray-900 dark:text-white">
              Connect to {{ selectedNetwork.ssid }}
            </h2>
            <button
              @click="selectedNetwork = null"
              class="inline-flex items-center px-2 py-1 text-gray-400 hover:text-gray-600"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>
          </div>

          <form @submit.prevent="handleConnectToNetwork" class="space-y-4">
            <div v-if="selectedNetwork.security !== 'Open'" class="space-y-2">
              <label for="password" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Password
              </label>
              <input
                id="password"
                v-model="password"
                type="password"
                placeholder="Enter network password"
                class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:placeholder-gray-400"
                required
                autocomplete="current-password"
              />
              <p class="text-xs text-gray-500 dark:text-gray-400">
                Security: {{ selectedNetwork.security }}
              </p>
            </div>

            <div v-else class="p-4 bg-green-50 dark:bg-green-900/20 rounded-md">
              <p class="text-sm text-green-800 dark:text-green-200">
                This is an open network and doesn't require a password.
              </p>
            </div>

            <div class="flex space-x-3">
              <button
                type="button"
                @click="selectedNetwork = null"
                class="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-800 font-medium py-3 px-4 rounded-lg transition-colors duration-200"
              >
                Cancel
              </button>
              <button
                type="submit"
                :disabled="isConnecting || (selectedNetwork.security !== 'Open' && !password)"
                class="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-4 rounded-lg transition-colors duration-200 flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <svg v-if="isConnecting" class="w-4 h-4 mr-2 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
                </svg>
                <svg v-else class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0"></path>
                </svg>
                {{ isConnecting ? 'Connecting...' : 'Connect' }}
              </button>
            </div>
          </form>
        </div>
      </div>

      <!-- Connected Network Actions -->
      <div v-if="selectedNetwork && selectedNetwork.connected" class="bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-700">
        <div class="p-6">
          <div class="text-center">
            <div class="w-12 h-12 bg-green-100 dark:bg-green-900/20 rounded-full flex items-center justify-center mx-auto mb-3">
              <svg class="w-6 h-6 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
              </svg>
            </div>
            <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-1">
              Already Connected
            </h3>
            <p class="text-sm text-gray-500 dark:text-gray-400 mb-4">
              You are currently connected to {{ selectedNetwork.ssid }}
            </p>
            <button
              @click="selectedNetwork = null"
              class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
// Meta
definePageMeta({
  title: 'WiFi Setup - Radio WiFi',
  description: 'Configure your WiFi connection'
})

// Reactive state
const networks = ref([])
const currentStatus = ref(null)
const selectedNetwork = ref(null)
const password = ref('')
const error = ref('')
const successMessage = ref('')
const isScanning = ref(false)
const isConnecting = ref(false)
const lastScanTime = ref(null)

// Auto-clear messages
const clearError = () => {
  error.value = ''
}

const clearSuccess = () => {
  successMessage.value = ''
}

const setError = (message) => {
  error.value = message
  setTimeout(clearError, 7000)
}

const setSuccess = (message) => {
  successMessage.value = message
  setTimeout(clearSuccess, 5000)
}

// Computed properties
const statusText = computed(() => {
  if (!currentStatus.value) return 'Unknown'
  const status = currentStatus.value.status
  const mode = currentStatus.value.mode

  if (mode === 'hotspot') return 'Hotspot Mode'
  if (status === 'connected' && currentStatus.value.ssid) return `Connected to ${currentStatus.value.ssid}`
  if (status === 'connecting') return 'Connecting...'
  return 'Disconnected'
})

const statusBadgeClass = computed(() => {
  if (!currentStatus.value) return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200'
  const status = currentStatus.value.status
  const mode = currentStatus.value.mode

  if (mode === 'hotspot') return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200'
  if (status === 'connected') return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200'
  if (status === 'connecting') return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200'
  return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200'
})

// Helper functions
const formatScanTime = (time) => {
  if (!time) return 'Never scanned'
  const now = Date.now()
  const diff = Math.floor((now - time) / 1000)
  if (diff < 60) return 'Just now'
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`
  const hours = Math.floor(diff / 3600)
  return `${hours}h ago`
}

const getSignalColor = (signal) => {
  if (!signal) return 'bg-gray-300 dark:bg-gray-600'
  if (signal >= 75) return 'bg-green-500'
  if (signal >= 50) return 'bg-yellow-500'
  if (signal >= 25) return 'bg-orange-500'
  return 'bg-red-500'
}

// API functions
const fetchWiFiStatus = async () => {
  try {
    const response = await $fetch('/api/wifi/status')
    if (response.success) {
      currentStatus.value = response.data
    } else {
      throw new Error(response.error || 'Failed to get WiFi status')
    }
  } catch (err) {
    console.error('Failed to get WiFi status:', err)
    // Don't show error for status fetch failures
  }
}

const handleScanNetworks = async () => {
  if (isScanning.value) return

  isScanning.value = true
  clearError()

  try {
    const response = await $fetch('/api/wifi/scan', { method: 'POST' })

    if (response.success) {
      networks.value = response.data || []
      lastScanTime.value = Date.now()
      console.log(`Found ${networks.value.length} networks`)
    } else {
      throw new Error(response.error || 'Failed to scan networks')
    }
  } catch (err) {
    console.error('Failed to scan networks:', err)
    const message = err instanceof Error ? err.message : 'Failed to scan for WiFi networks. Please try again.'
    setError(message)
  } finally {
    isScanning.value = false
  }
}

const selectNetwork = (network) => {
  if (network.connected) {
    selectedNetwork.value = network
    return
  }

  selectedNetwork.value = network
  password.value = ''
  clearError()
  clearSuccess()
}

const handleConnectToNetwork = async () => {
  if (!selectedNetwork.value) return

  isConnecting.value = true
  clearError()
  clearSuccess()

  try {
    const payload = {
      ssid: selectedNetwork.value.ssid,
      password: password.value || '',
      security: selectedNetwork.value.security
    }

    const response = await $fetch('/api/wifi/connect', {
      method: 'POST',
      body: payload
    })

    if (response.success) {
      setSuccess(`Connecting to ${selectedNetwork.value.ssid}. The system will switch to client mode.`)
      selectedNetwork.value = null
      password.value = ''

      // Refresh status after a delay
      setTimeout(async () => {
        await fetchWiFiStatus()
      }, 2000)
    } else {
      throw new Error(response.error || 'Failed to connect to network')
    }
  } catch (err) {
    console.error('Failed to connect to network:', err)
    const message = err instanceof Error ? err.message : 'Failed to connect to network. Please check your password and try again.'
    setError(message)
  } finally {
    isConnecting.value = false
  }
}

// Initialize on mount
onMounted(async () => {
  await fetchWiFiStatus()
  if (networks.value.length === 0) {
    await handleScanNetworks()
  }
})

// Head configuration
useHead({
  title: 'WiFi Setup - Radio WiFi Configuration',
  meta: [
    { name: 'description', content: 'Configure your WiFi connection - scan for networks and connect securely' }
  ]
})
</script>
