// app/components/SignalStrength.vue
<template>
  <div class="signal-strength" :class="sizeClass">
    <div
      v-for="bar in 4"
      :key="bar"
      class="signal-bar"
      :class="{
        'signal-active': bar <= activeBars,
        'signal-inactive': bar > activeBars
      }"
    />
  </div>
</template>

<script setup lang="ts">
interface Props {
  strength: number
  size?: 'xs' | 'sm' | 'md' | 'lg'
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md'
})

// Calculate number of active bars based on signal strength
const activeBars = computed(() => {
  if (props.strength >= 75) return 4
  if (props.strength >= 50) return 3
  if (props.strength >= 25) return 2
  if (props.strength > 0) return 1
  return 0
})

// Size classes
const sizeClass = computed(() => {
  switch (props.size) {
    case 'xs': return 'signal-xs'
    case 'sm': return 'signal-sm'
    case 'md': return 'signal-md'
    case 'lg': return 'signal-lg'
    default: return 'signal-md'
  }
})

// Signal strength color
const signalColor = computed(() => {
  if (props.strength >= 75) return 'text-green-500'
  if (props.strength >= 50) return 'text-yellow-500'
  if (props.strength >= 25) return 'text-orange-500'
  return 'text-red-500'
})
</script>

<style scoped>
.signal-strength {
  @apply flex items-end space-x-0.5;
}

.signal-bar {
  @apply bg-current rounded-sm transition-colors duration-200;
}

/* Size variants */
.signal-xs .signal-bar {
  @apply w-0.5;
}

.signal-xs .signal-bar:nth-child(1) { @apply h-1; }
.signal-xs .signal-bar:nth-child(2) { @apply h-1.5; }
.signal-xs .signal-bar:nth-child(3) { @apply h-2; }
.signal-xs .signal-bar:nth-child(4) { @apply h-2.5; }

.signal-sm .signal-bar {
  @apply w-0.5;
}

.signal-sm .signal-bar:nth-child(1) { @apply h-1; }
.signal-sm .signal-bar:nth-child(2) { @apply h-2; }
.signal-sm .signal-bar:nth-child(3) { @apply h-3; }
.signal-sm .signal-bar:nth-child(4) { @apply h-4; }

.signal-md .signal-bar {
  @apply w-1;
}

.signal-md .signal-bar:nth-child(1) { @apply h-1.5; }
.signal-md .signal-bar:nth-child(2) { @apply h-2.5; }
.signal-md .signal-bar:nth-child(3) { @apply h-3.5; }
.signal-md .signal-bar:nth-child(4) { @apply h-4; }

.signal-lg .signal-bar {
  @apply w-1;
}

.signal-lg .signal-bar:nth-child(1) { @apply h-2; }
.signal-lg .signal-bar:nth-child(2) { @apply h-3; }
.signal-lg .signal-bar:nth-child(3) { @apply h-4; }
.signal-lg .signal-bar:nth-child(4) { @apply h-5; }

/* Signal strength colors */
.signal-active {
  @apply text-green-500;
}

.signal-inactive {
  @apply text-gray-300 dark:text-gray-600;
}

/* Signal strength based coloring */
.signal-strength:has(.signal-bar:nth-child(4).signal-active) .signal-active {
  @apply text-green-500;
}

.signal-strength:has(.signal-bar:nth-child(3).signal-active):not(:has(.signal-bar:nth-child(4).signal-active)) .signal-active {
  @apply text-yellow-500;
}

.signal-strength:has(.signal-bar:nth-child(2).signal-active):not(:has(.signal-bar:nth-child(3).signal-active)) .signal-active {
  @apply text-orange-500;
}

.signal-strength:has(.signal-bar:nth-child(1).signal-active):not(:has(.signal-bar:nth-child(2).signal-active)) .signal-active {
  @apply text-red-500;
}
</style>

// frontend/src/lib/components/SignalStrength.svelte
<script lang="ts">
	interface Props {
		signal?: number;
		size?: 'sm' | 'md' | 'lg';
	}

	let { signal, size = 'md' }: Props = $props();

	const bars = $derived(signal ? Math.ceil((signal / 100) * 4) : 0);

	const color = $derived(() => {
		if (!signal) return 'text-gray-400';
		if (signal >= 75) return 'text-green-500';
		if (signal >= 50) return 'text-yellow-500';
		if (signal >= 25) return 'text-orange-500';
		return 'text-red-500';
	});

	const sizeClass = $derived(({ sm: 'w-4 h-4', md: 'w-5 h-5', lg: 'w-6 h-6' } as const)[size]);
</script>

<div class="flex items-center space-x-1 {color()}">
	<svg class={sizeClass} viewBox="0 0 24 24" fill="none" stroke="currentColor">
		<rect x="2" y="18" width="2" height="4" fill={bars >= 1 ? 'currentColor' : 'none'} stroke="currentColor" stroke-width="0.5" />
		<rect x="6" y="15" width="2" height="7" fill={bars >= 2 ? 'currentColor' : 'none'} stroke="currentColor" stroke-width="0.5" />
		<rect x="10" y="12" width="2" height="10" fill={bars >= 3 ? 'currentColor' : 'none'} stroke="currentColor" stroke-width="0.5" />
		<rect x="14" y="9" width="2" height="13" fill={bars >= 4 ? 'currentColor' : 'none'} stroke="currentColor" stroke-width="0.5" />
	</svg>
	{#if signal !== undefined}
		<span class="text-xs font-medium">{signal}%</span>
	{/if}
</div>
